spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
  datasource:
    url: jdbc:h2:mem:memDb
    driverClassName: org.h2.Driver
    username: sa
    password: